### ISSUE TITLE
Does not display rewards if started for the first time

### ISSUE THREAD

**Issue by atomicptr** [Xeio/VoidRewardParser#4]
When the "PrimeData.data" file doesn't exist the app is not able to display rewards. Restarting the program solves that issue though.

**Comment by Xeio** [comment]
Hrmmm, weird. It should automatically create that file the first time you run it (and then saves it again every time you close the app).

**Comment by atomicptr** [comment]
Yes it does that but it can't display the rewards for me the first time

**Comment by Xeio** [comment]
Ah, found the issue, seems there's a race condition with the bindings, and it works occasionally which is probably how I missed that...

Fix is in, I'll have to put together a release when I get a chance.

**Comment by Xeio** [comment]
Fixed in release v0.8
