### ISSUE TITLE
AKBRONCO PRIME parts also show up as BRONCO PRIME

### ISSUE THREAD

**Issue by joshdurham** [Xeio/VoidRewardParser#6]
If you get an AKBRONCO PRIME part, it will also match on the BRONCO PRIME parts (you'll see both in the parser.)

**Comment by vith** [comment]
I just had the opposite problem. Both `BRONCO PRIME BLUEPRINT` and `AKBRONCO PRIME BLUEPRINT` dropped but only Bronco, Boar, and Hikou showed up in VoidRewardParser.
Could have just been the map/player names interfering though. https://i.imgur.com/ZkR6MLy.jpg

**Comment by Xeio** [comment]
Yea, that's screenshot is pretty much text/icons covering the item name. Can't really work around that. Could try and bug DE to fix it but good luck... ;)

I may be able to stop AK part false-positives showing up, but as it currently is I'll need to refactor how the tool uses the resulting OCR result. I've been thinking about doing that to try and auto-parse the Prime Part inventory screen counts, but I'd need to dedicate more time to that so the false positives will probably stick around for the moment.

On the other hand, DE announced they'll be adding at least rarity indicators to the Void Mission Rewards screen, so I'm not sure how important this project will be going forward anyway.
