### ISSUE TITLE
Stale entries remain when window is automatically raised

### ISSUE THREAD

**Issue by vith** [Xeio/VoidRewardParser#8]
When I get to the rewards screen, the VoidRewardParser window will pop up but it will have for example 5+ items (I believe it's entries that remained there from the relic selection screen before the mission). After alt tabbing back and forth it will then go down to the 3 actual items (since forma isn't included).

At least once this has happened (5 old items listed in VRP) while the game said "Please wait... Retrieving rewards from the server..." before any items were presented in game.

**Comment by Xeio** [comment]
Should be fixed in release v0.8
